//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visigo.Sharepoint.FormsBasedAuthentication.ResourcesAppGlobal {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FBAPackWebPages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FBAPackWebPages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Visigo.Sharepoint.FormsBasedAuthentication.ResourcesAppGlobal.FBAPackWebPages", typeof(FBAPackWebPages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Locked.
        /// </summary>
        internal static string AccountLockedHeaderText {
            get {
                return ResourceManager.GetString("AccountLockedHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncheck the box to unlock the user&apos;s account..
        /// </summary>
        internal static string AccountLockedLabelText {
            get {
                return ResourceManager.GetString("AccountLockedLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked the account is locked..
        /// </summary>
        internal static string AccountLockedToolTipText {
            get {
                return ResourceManager.GetString("AccountLockedToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the box if the user&apos;s account is active..
        /// </summary>
        internal static string ActiveCheckBoxLabelText {
            get {
                return ResourceManager.GetString("ActiveCheckBoxLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked the account is active..
        /// </summary>
        internal static string ActiveCheckBoxToolTipText {
            get {
                return ResourceManager.GetString("ActiveCheckBoxToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string ActiveColHeaderText {
            get {
                return ResourceManager.GetString("ActiveColHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows a user to change their login password..
        /// </summary>
        internal static string ChangePassword_Desc {
            get {
                return ResourceManager.GetString("ChangePassword_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string ChangePassword_Title {
            get {
                return ResourceManager.GetString("ChangePassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter and confirm the password:.
        /// </summary>
        internal static string ConfirmPasswordLabelText {
            get {
                return ResourceManager.GetString("ConfirmPasswordLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password..
        /// </summary>
        internal static string ConfirmPasswordToolTipText {
            get {
                return ResourceManager.GetString("ConfirmPasswordToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string CreatedColHeaderText {
            get {
                return ResourceManager.GetString("CreatedColHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteButtonText {
            get {
                return ResourceManager.GetString("DeleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm User Delete.
        /// </summary>
        internal static string DeleteConfirmHeaderText {
            get {
                return ResourceManager.GetString("DeleteConfirmHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm that you want to delete the user &apos;{0}&apos;.
        /// </summary>
        internal static string DeleteConfirmLabelText {
            get {
                return ResourceManager.GetString("DeleteConfirmLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to permenantly delete this user?.
        /// </summary>
        internal static string DeleteConfirmText {
            get {
                return ResourceManager.GetString("DeleteConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteContextMenuText {
            get {
                return ResourceManager.GetString("DeleteContextMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Forms Based Authentication Role.
        /// </summary>
        internal static string DeleteRole_Title {
            get {
                return ResourceManager.GetString("DeleteRole_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove all users from this role and permenantly delete this role?.
        /// </summary>
        internal static string DeleteRoleConfirmText {
            get {
                return ResourceManager.GetString("DeleteRoleConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Forms Based Authentication User.
        /// </summary>
        internal static string DeleteUser_Title {
            get {
                return ResourceManager.GetString("DeleteUser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A username for that e-mail address already exists. Please enter a different e-mail address..
        /// </summary>
        internal static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already exists. Please enter a different user name..
        /// </summary>
        internal static string DuplicateUserName {
            get {
                return ResourceManager.GetString("DuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditContextMenuText {
            get {
                return ResourceManager.GetString("EditContextMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Forms Based Authentication User.
        /// </summary>
        internal static string EditUser_Title {
            get {
                return ResourceManager.GetString("EditUser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string EmailColHeaderText {
            get {
                return ResourceManager.GetString("EmailColHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Roles:.
        /// </summary>
        internal static string EnableRolesLabelText {
            get {
                return ResourceManager.GetString("EnableRolesLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Roles.
        /// </summary>
        internal static string EnableRolesToolTipText {
            get {
                return ResourceManager.GetString("EnableRolesToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password..
        /// </summary>
        internal static string EnterPasswordToolTipText {
            get {
                return ResourceManager.GetString("EnterPasswordToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while adding this user to SharePoint.
        /// </summary>
        internal static string ErrorAddingToSharePoint {
            get {
                return ResourceManager.GetString("ErrorAddingToSharePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string FullNameColHeaderText {
            get {
                return ResourceManager.GetString("FullNameColHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group / Roles.
        /// </summary>
        internal static string GroupHeaderText {
            get {
                return ResourceManager.GetString("GroupHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose at least one group/role to add the user to:.
        /// </summary>
        internal static string GroupLabelText {
            get {
                return ResourceManager.GetString("GroupLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the groups / roles for this user..
        /// </summary>
        internal static string GroupToolTipText {
            get {
                return ResourceManager.GetString("GroupToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password retrieval answer provided is invalid. Please check the value and try again..
        /// </summary>
        internal static string InvalidAnswer {
            get {
                return ResourceManager.GetString("InvalidAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The e-mail address provided is invalid. Please check the value and try again..
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password provided is invalid. Please enter a valid password value..
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password invalid. New Password length minimum: {0}. Non-alphanumeric characters required: {1}..
        /// </summary>
        internal static string InvalidPasswordChars {
            get {
                return ResourceManager.GetString("InvalidPasswordChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password invalid. New Password length minimum: {0}. Non-alphanumeric characters required: {1}. Password Strength Regular Expression: {2}..
        /// </summary>
        internal static string InvalidPasswordCharsRegex {
            get {
                return ResourceManager.GetString("InvalidPasswordCharsRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password retrieval question provided is invalid. Please check the value and try again..
        /// </summary>
        internal static string InvalidQuestion {
            get {
                return ResourceManager.GetString("InvalidQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name provided is invalid. Please check the value and try again..
        /// </summary>
        internal static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsInSharePoint.
        /// </summary>
        internal static string IsInSharePointColHeaderText {
            get {
                return ResourceManager.GetString("IsInSharePointColHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Login.
        /// </summary>
        internal static string LastLoginColHeaderText {
            get {
                return ResourceManager.GetString("LastLoginColHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        internal static string LockedColHeaderText {
            get {
                return ResourceManager.GetString("LockedColHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership Approved:.
        /// </summary>
        internal static string MembershipApprovedLabelText {
            get {
                return ResourceManager.GetString("MembershipApprovedLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership Approved.
        /// </summary>
        internal static string MembershipApprovedToolTipText {
            get {
                return ResourceManager.GetString("MembershipApprovedToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:MembershipRequest=&quot;fba:MembershipRequest&quot;&gt;
        ///  &lt;xsl:template match=&quot;/&quot;&gt;
        ///    &lt;html&gt;
        ///      &lt;head&gt;
        ///        &lt;title&gt;Membership Approved&lt;/title&gt;
        ///      &lt;/head&gt;
        ///      &lt;body&gt;
        ///        &lt;div&gt;
        ///            &lt;br /&gt;
        ///            &lt;p&gt;Your request for an account on &lt;xsl:value-of select=&quot;MembershipRequest:get_SiteName()&quot; /&gt; has been approved and you have been granted access.&lt;/p&gt;
        ///            &lt;p&gt;You [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MembershipApprovedXSLT {
            get {
                return ResourceManager.GetString("MembershipApprovedXSLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XSL templates used for sending emails..
        /// </summary>
        internal static string MembershipEmailTemplateHeaderDesc {
            get {
                return ResourceManager.GetString("MembershipEmailTemplateHeaderDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership Emails.
        /// </summary>
        internal static string MembershipEmailTemplateHeaderText {
            get {
                return ResourceManager.GetString("MembershipEmailTemplateHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership Error:.
        /// </summary>
        internal static string MembershipErrorLabelText {
            get {
                return ResourceManager.GetString("MembershipErrorLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership Error.
        /// </summary>
        internal static string MembershipErrorToolTipText {
            get {
                return ResourceManager.GetString("MembershipErrorToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Membership Provider has not been configured correctly. Check the web.config setttings for this web application..
        /// </summary>
        internal static string MembershipNotConfigured {
            get {
                return ResourceManager.GetString("MembershipNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These options control the functionality of the FBA web parts..
        /// </summary>
        internal static string MembershipOptionHeaderDesc {
            get {
                return ResourceManager.GetString("MembershipOptionHeaderDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership Options.
        /// </summary>
        internal static string MembershipOptionHeaderText {
            get {
                return ResourceManager.GetString("MembershipOptionHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership Pending:.
        /// </summary>
        internal static string MembershipPendingLabelText {
            get {
                return ResourceManager.GetString("MembershipPendingLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership Pending.
        /// </summary>
        internal static string MembershipPendingToolTipText {
            get {
                return ResourceManager.GetString("MembershipPendingToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:MembershipRequest=&quot;fba:MembershipRequest&quot;&gt;
        ///  &lt;xsl:template match=&quot;/&quot;&gt;
        ///    &lt;html&gt;
        ///      &lt;head&gt;
        ///        &lt;title&gt;Membership Pending&lt;/title&gt;
        ///      &lt;/head&gt;
        ///      &lt;body&gt;
        ///        &lt;div&gt;
        ///          &lt;br /&gt;
        ///          &lt;p&gt;Thank you for requesting a Membership on &lt;xsl:value-of select=&quot;MembershipRequest:get_SiteName()&quot; /&gt;.&lt;/p&gt;
        ///
        ///          &lt;p&gt;You will receive an email with a temporary passwo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MembershipPendingXSLT {
            get {
                return ResourceManager.GetString("MembershipPendingXSLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership Rejected:.
        /// </summary>
        internal static string MembershipRejectedLabelText {
            get {
                return ResourceManager.GetString("MembershipRejectedLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership Rejected.
        /// </summary>
        internal static string MembershipRejectedToolTipText {
            get {
                return ResourceManager.GetString("MembershipRejectedToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:MembershipRequest=&quot;fba:MembershipRequest&quot;&gt;
        ///  &lt;xsl:template match=&quot;/&quot;&gt;
        ///    &lt;html&gt;
        ///      &lt;head&gt;
        ///        &lt;title&gt;Membership Request Rejected&lt;/title&gt;
        ///      &lt;/head&gt;
        ///      &lt;body&gt;
        ///        &lt;div&gt;
        ///          &lt;p&gt;Your membership request on &lt;xsl:value-of select=&quot;MembershipRequest:get_SiteName()&quot; /&gt; has been rejected.&lt;/p&gt;
        ///
        ///          &lt;p&gt;If you feel that this is an error please try again or  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MembershipRejectedXSLT {
            get {
                return ResourceManager.GetString("MembershipRejectedXSLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These pages can be used in the email XSLT templates using the following syntax:
        ///&lt;pre&gt;
        ///&amp;lt;xsl:value-of select=&quot;MembershipRequest:get_ChangePasswordURL()&quot; /&amp;gt;
        ///&amp;lt;xsl:value-of select=&quot;MembershipRequest:get_PasswordQuestionURL()&quot; /&amp;gt;
        ///&amp;lt;xsl:value-of select=&quot;MembershipRequest:get_ThankYouURL()&quot; /&amp;gt;
        ///&lt;/pre&gt;.
        /// </summary>
        internal static string MembershipSiteReviewHeaderDesc {
            get {
                return ResourceManager.GetString("MembershipSiteReviewHeaderDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership Review Site URLs.
        /// </summary>
        internal static string MembershipSiteReviewHeaderText {
            get {
                return ResourceManager.GetString("MembershipSiteReviewHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot import this Web Part..
        /// </summary>
        internal static string MissingAssemblyMsg {
            get {
                return ResourceManager.GetString("MissingAssemblyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        internal static string ModifiedColHeaderText {
            get {
                return ResourceManager.GetString("ModifiedColHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password:.
        /// </summary>
        internal static string NewPasswordLabelText {
            get {
                return ResourceManager.GetString("NewPasswordLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string NewPasswordToolTipText {
            get {
                return ResourceManager.GetString("NewPasswordToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Forms Based Authentication Role.
        /// </summary>
        internal static string NewRole_Title {
            get {
                return ResourceManager.GetString("NewRole_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Role.
        /// </summary>
        internal static string NewRoleLabelText {
            get {
                return ResourceManager.GetString("NewRoleLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Forms Based Authentication User.
        /// </summary>
        internal static string NewUser_Title {
            get {
                return ResourceManager.GetString("NewUser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User.
        /// </summary>
        internal static string NewUserLabelText {
            get {
                return ResourceManager.GetString("NewUserLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This also sets the location of the page for the Change Password menu item..
        /// </summary>
        internal static string PasswordChangePageExampleText {
            get {
                return ResourceManager.GetString("PasswordChangePageExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password Page:.
        /// </summary>
        internal static string PasswordChangePageLabelText {
            get {
                return ResourceManager.GetString("PasswordChangePageLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password Page.
        /// </summary>
        internal static string PasswordChangePageToolTipText {
            get {
                return ResourceManager.GetString("PasswordChangePageToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset the password? The user will be emailed the new password.
        /// </summary>
        internal static string PasswordConfirmText {
            get {
                return ResourceManager.GetString("PasswordConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordHeaderText {
            get {
                return ResourceManager.GetString("PasswordHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Question Page:.
        /// </summary>
        internal static string PasswordQuestionPageLabelText {
            get {
                return ResourceManager.GetString("PasswordQuestionPageLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Question Page.
        /// </summary>
        internal static string PasswordQuestionPageToolTipText {
            get {
                return ResourceManager.GetString("PasswordQuestionPageToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Recovery:.
        /// </summary>
        internal static string PasswordRecoveryLabelText {
            get {
                return ResourceManager.GetString("PasswordRecoveryLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Recovery.
        /// </summary>
        internal static string PasswordRecoveryToolTipText {
            get {
                return ResourceManager.GetString("PasswordRecoveryToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:MembershipRequest=&quot;fba:MembershipRequest&quot;&gt;
        ///  &lt;xsl:template match=&quot;/&quot;&gt;
        ///    &lt;html&gt;
        ///      &lt;head&gt;
        ///        &lt;title&gt;Membership Password Recovery&lt;/title&gt;
        ///      &lt;/head&gt;
        ///      &lt;body&gt;
        ///        &lt;div&gt;
        ///            &lt;p&gt;You have requested this mail because you have forgotten your password to &lt;xsl:value-of select=&quot;MembershipRequest:get_SiteName()&quot; /&gt;.&lt;/p&gt;
        ///
        ///          &lt;p&gt;
        ///            Your user [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PasswordRecoveryXSLT {
            get {
                return ResourceManager.GetString("PasswordRecoveryXSLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authentication provider returned an error. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        internal static string ProviderError {
            get {
                return ResourceManager.GetString("ProviderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply To Email Address:.
        /// </summary>
        internal static string ReplyToLabelText {
            get {
                return ResourceManager.GetString("ReplyToLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply To.
        /// </summary>
        internal static string ReplyToToolTipText {
            get {
                return ResourceManager.GetString("ReplyToToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to a randomly generated password.
        /// </summary>
        internal static string ResetAutoPasswordText {
            get {
                return ResourceManager.GetString("ResetAutoPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new password is: {0}.
        /// </summary>
        internal static string ResetPasswordBody {
            get {
                return ResourceManager.GetString("ResetPasswordBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string ResetPasswordButtonText {
            get {
                return ResourceManager.GetString("ResetPasswordButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error setting the new password during the password reset process. If this error persists, there may be an issue with your membership provider..
        /// </summary>
        internal static string ResetPasswordChangePasswordError {
            get {
                return ResourceManager.GetString("ResetPasswordChangePasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset this user&apos;s password?.
        /// </summary>
        internal static string ResetPasswordConfirmText {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string ResetPasswordContextMenuText {
            get {
                return ResourceManager.GetString("ResetPasswordContextMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resets the user&apos;s password..
        /// </summary>
        internal static string ResetPasswordDescText {
            get {
                return ResourceManager.GetString("ResetPasswordDescText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Template:.
        /// </summary>
        internal static string ResetPasswordEmailTemplateLabelText {
            get {
                return ResourceManager.GetString("ResetPasswordEmailTemplateLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Template.
        /// </summary>
        internal static string ResetPasswordEmailTemplateToolTipText {
            get {
                return ResourceManager.GetString("ResetPasswordEmailTemplateToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string ResetPasswordHeaderText {
            get {
                return ResourceManager.GetString("ResetPasswordHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password:.
        /// </summary>
        internal static string ResetPasswordLabelText {
            get {
                return ResourceManager.GetString("ResetPasswordLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password for user &apos;{0}&apos;.
        /// </summary>
        internal static string ResetPasswordMsg {
            get {
                return ResourceManager.GetString("ResetPasswordMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email the user their new password.
        /// </summary>
        internal static string ResetPasswordSendEmailLabelText {
            get {
                return ResourceManager.GetString("ResetPasswordSendEmailLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email the user their new password.
        /// </summary>
        internal static string ResetPasswordSendEmailToolTipText {
            get {
                return ResourceManager.GetString("ResetPasswordSendEmailToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reset for {0}.
        /// </summary>
        internal static string ResetPasswordSubject {
            get {
                return ResourceManager.GetString("ResetPasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string ResetPasswordToolTipText {
            get {
                return ResourceManager.GetString("ResetPasswordToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current membershipprovider settings prevent a user&apos;s password from being reset. To allow for resetting of a password by an administrator, you must have enablePasswordReset=&quot;true&quot; and requiresQuestionAndAnswer=&quot;false&quot; in your membership provider settings in your web.config..
        /// </summary>
        internal static string ResetPasswordUnavailable {
            get {
                return ResourceManager.GetString("ResetPasswordUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string ResetPasswordUser_Title {
            get {
                return ResourceManager.GetString("ResetPasswordUser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:MembershipRequest=&quot;fba:MembershipRequest&quot;&gt;
        ///  &lt;xsl:template match=&quot;/&quot;&gt;
        ///    &lt;html&gt;
        ///      &lt;head&gt;
        ///        &lt;title&gt;Password Reset for &lt;xsl:value-of select=&quot;MembershipRequest:get_UserName()&quot; /&gt;&lt;/title&gt;
        ///      &lt;/head&gt;
        ///      &lt;body&gt;
        ///        &lt;div&gt;
        ///			&lt;p&gt;Your new password is: &lt;xsl:value-of select=&quot;MembershipRequest:get_Password()&quot; /&gt;&lt;/p&gt;
        ///        &lt;/div&gt;
        ///      &lt;/body&gt;
        ///    &lt;/html&gt;
        ///  &lt;/xs [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ResetPasswordXSLT {
            get {
                return ResourceManager.GetString("ResetPasswordXSLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the user&apos;s new password.
        /// </summary>
        internal static string ResetSelectPasswordText {
            get {
                return ResourceManager.GetString("ResetSelectPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Membership Requests:.
        /// </summary>
        internal static string ReviewMembershipRequestLabelText {
            get {
                return ResourceManager.GetString("ReviewMembershipRequestLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Membership Requests:.
        /// </summary>
        internal static string ReviewMembershipRequestToolTipText {
            get {
                return ResourceManager.GetString("ReviewMembershipRequestToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string RoleColHeaderText {
            get {
                return ResourceManager.GetString("RoleColHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Already Exists..
        /// </summary>
        internal static string RoleExistenceMsg {
            get {
                return ResourceManager.GetString("RoleExistenceMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        internal static string RoleNameHeaderText {
            get {
                return ResourceManager.GetString("RoleNameHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the Role Name:.
        /// </summary>
        internal static string RoleNameLabelText {
            get {
                return ResourceManager.GetString("RoleNameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role doesn&apos;t exist..
        /// </summary>
        internal static string RoleNotExistenceMsg {
            get {
                return ResourceManager.GetString("RoleNotExistenceMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this page to manage forms based authentication roles..
        /// </summary>
        internal static string RolesMgmt_Desc {
            get {
                return ResourceManager.GetString("RolesMgmt_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Forms Based Authentication Users and Roles.
        /// </summary>
        internal static string RolesMgmt_Title {
            get {
                return ResourceManager.GetString("RolesMgmt_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveButonText {
            get {
                return ResourceManager.GetString("SaveButonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchButtonText {
            get {
                return ResourceManager.GetString("SearchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        internal static string SearchLabelText {
            get {
                return ResourceManager.GetString("SearchLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Answer.
        /// </summary>
        internal static string SecurityAnswerHeaderText {
            get {
                return ResourceManager.GetString("SecurityAnswerHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Question.
        /// </summary>
        internal static string SecurityQuestionHeaderText {
            get {
                return ResourceManager.GetString("SecurityQuestionHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send E-mail.
        /// </summary>
        internal static string SendEmailHeaderText {
            get {
                return ResourceManager.GetString("SendEmailHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send welcome e-mail to the new user.
        /// </summary>
        internal static string SendMailLabelText {
            get {
                return ResourceManager.GetString("SendMailLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this page to manage forms based authentication site configuration such as site URLs..
        /// </summary>
        internal static string SiteConfig_Desc {
            get {
                return ResourceManager.GetString("SiteConfig_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Forms Based Authentication Configuration.
        /// </summary>
        internal static string SiteConfig_Title {
            get {
                return ResourceManager.GetString("SiteConfig_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You Page:.
        /// </summary>
        internal static string ThankYouPageLabelText {
            get {
                return ResourceManager.GetString("ThankYouPageLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You Page.
        /// </summary>
        internal static string ThankYouPageToolTipText {
            get {
                return ResourceManager.GetString("ThankYouPageToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the user&apos;s email address:.
        /// </summary>
        internal static string TypeEmailAddrLabelText {
            get {
                return ResourceManager.GetString("TypeEmailAddrLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the Full Name:.
        /// </summary>
        internal static string TypeFullNameLabelText {
            get {
                return ResourceManager.GetString("TypeFullNameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the security answer:.
        /// </summary>
        internal static string TypeSecurityALableText {
            get {
                return ResourceManager.GetString("TypeSecurityALableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the security question:.
        /// </summary>
        internal static string TypeSecurityQLableText {
            get {
                return ResourceManager.GetString("TypeSecurityQLableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the User Name:.
        /// </summary>
        internal static string TypeUserNameLabelText {
            get {
                return ResourceManager.GetString("TypeUserNameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred. If the problem persists, please contact your system administrator or check the SharePoint log for further details..
        /// </summary>
        internal static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this page to manage forms based authentication users.
        /// </summary>
        internal static string UserMgmt_Desc {
            get {
                return ResourceManager.GetString("UserMgmt_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Forms Based Authentication Users.
        /// </summary>
        internal static string UserMgmt_Title {
            get {
                return ResourceManager.GetString("UserMgmt_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string UserNameColHeaderText {
            get {
                return ResourceManager.GetString("UserNameColHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is read only:.
        /// </summary>
        internal static string UserNameReadonlyLabelText {
            get {
                return ResourceManager.GetString("UserNameReadonlyLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Not Found.
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user creation request has been canceled. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        internal static string UserRejected {
            get {
                return ResourceManager.GetString("UserRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users In Role.
        /// </summary>
        internal static string UsersInRoleColHeaderText {
            get {
                return ResourceManager.GetString("UsersInRoleColHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} users in this role..
        /// </summary>
        internal static string UsersInRoleMsg {
            get {
                return ResourceManager.GetString("UsersInRoleMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The currently installed version of the FBA Pack..
        /// </summary>
        internal static string VersionHeaderDesc {
            get {
                return ResourceManager.GetString("VersionHeaderDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string VersionHeaderText {
            get {
                return ResourceManager.GetString("VersionHeaderText", resourceCulture);
            }
        }
    }
}
