//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visigo.Sharepoint.FormsBasedAuthentication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FBAPackMenus {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FBAPackMenus() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Visigo.Sharepoint.FormsBasedAuthentication.Resources.FBAPackMenus", typeof(FBAPackMenus).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your current password..
        /// </summary>
        internal static string FBAChangePassword_Desc {
            get {
                return ResourceManager.GetString("FBAChangePassword_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string FBAChangePassword_Title {
            get {
                return ResourceManager.GetString("FBAChangePassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage the membership requests for this site collection..
        /// </summary>
        internal static string FBAMembershipRequestManagement_Desc {
            get {
                return ResourceManager.GetString("FBAMembershipRequestManagement_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FBA Membership Request Management.
        /// </summary>
        internal static string FBAMembershipRequestManagement_Title {
            get {
                return ResourceManager.GetString("FBAMembershipRequestManagement_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage the Forms Based Authentication roles in this site collection..
        /// </summary>
        internal static string FBARoleManagement_Desc {
            get {
                return ResourceManager.GetString("FBARoleManagement_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FBA Role Management.
        /// </summary>
        internal static string FBARoleManagement_Title {
            get {
                return ResourceManager.GetString("FBARoleManagement_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage the Forms Based Authentication site FBA properties..
        /// </summary>
        internal static string FBASiteConfiguration_Desc {
            get {
                return ResourceManager.GetString("FBASiteConfiguration_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FBA Site Configuration.
        /// </summary>
        internal static string FBASiteConfiguration_Title {
            get {
                return ResourceManager.GetString("FBASiteConfiguration_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage the Forms Based Authentication users in this site collection..
        /// </summary>
        internal static string FBAUserManagement_Desc {
            get {
                return ResourceManager.GetString("FBAUserManagement_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FBA User Management.
        /// </summary>
        internal static string FBAUserManagement_Title {
            get {
                return ResourceManager.GetString("FBAUserManagement_Title", resourceCulture);
            }
        }
    }
}
