//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visigo.Sharepoint.FormsBasedAuthentication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FBAPackChangePasswordWebPart {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FBAPackChangePasswordWebPart() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Visigo.Sharepoint.FormsBasedAuthentication.Resources.FBAPackChangePasswordWebPart" +
                            "", typeof(FBAPackChangePasswordWebPart).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string CancelButtonImageUrl_Category {
            get {
                return ResourceManager.GetString("CancelButtonImageUrl_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CancelButtonImageUrl_DefaultValue {
            get {
                return ResourceManager.GetString("CancelButtonImageUrl_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CancelButtonImageUrl_Description {
            get {
                return ResourceManager.GetString("CancelButtonImageUrl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Button Image Url.
        /// </summary>
        internal static string CancelButtonImageUrl_FriendlyName {
            get {
                return ResourceManager.GetString("CancelButtonImageUrl_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string CancelButtonText_Category {
            get {
                return ResourceManager.GetString("CancelButtonText_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelButtonText_DefaultValue {
            get {
                return ResourceManager.GetString("CancelButtonText_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CancelButtonText_Description {
            get {
                return ResourceManager.GetString("CancelButtonText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Button Text.
        /// </summary>
        internal static string CancelButtonText_FriendlyName {
            get {
                return ResourceManager.GetString("CancelButtonText_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string CancelButtonType_Category {
            get {
                return ResourceManager.GetString("CancelButtonType_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string CancelButtonType_DefaultValue {
            get {
                return ResourceManager.GetString("CancelButtonType_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CancelButtonType_Description {
            get {
                return ResourceManager.GetString("CancelButtonType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Button Type.
        /// </summary>
        internal static string CancelButtonType_FriendlyName {
            get {
                return ResourceManager.GetString("CancelButtonType_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string CancelDestinationPageUrl_Category {
            get {
                return ResourceManager.GetString("CancelDestinationPageUrl_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CancelDestinationPageUrl_DefaultValue {
            get {
                return ResourceManager.GetString("CancelDestinationPageUrl_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CancelDestinationPageUrl_Description {
            get {
                return ResourceManager.GetString("CancelDestinationPageUrl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Destination Page Url.
        /// </summary>
        internal static string CancelDestinationPageUrl_FriendlyName {
            get {
                return ResourceManager.GetString("CancelDestinationPageUrl_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string ChangePasswordButtonImageUrl_Category {
            get {
                return ResourceManager.GetString("ChangePasswordButtonImageUrl_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChangePasswordButtonImageUrl_DefaultValue {
            get {
                return ResourceManager.GetString("ChangePasswordButtonImageUrl_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChangePasswordButtonImageUrl_Description {
            get {
                return ResourceManager.GetString("ChangePasswordButtonImageUrl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password Button Image Url.
        /// </summary>
        internal static string ChangePasswordButtonImageUrl_FriendlyName {
            get {
                return ResourceManager.GetString("ChangePasswordButtonImageUrl_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string ChangePasswordButtonText_Category {
            get {
                return ResourceManager.GetString("ChangePasswordButtonText_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string ChangePasswordButtonText_DefaultValue {
            get {
                return ResourceManager.GetString("ChangePasswordButtonText_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChangePasswordButtonText_Description {
            get {
                return ResourceManager.GetString("ChangePasswordButtonText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password Button Text.
        /// </summary>
        internal static string ChangePasswordButtonText_FriendlyName {
            get {
                return ResourceManager.GetString("ChangePasswordButtonText_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string ChangePasswordButtonType_Category {
            get {
                return ResourceManager.GetString("ChangePasswordButtonType_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string ChangePasswordButtonType_DefaultValue {
            get {
                return ResourceManager.GetString("ChangePasswordButtonType_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChangePasswordButtonType_Description {
            get {
                return ResourceManager.GetString("ChangePasswordButtonType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password Button Type.
        /// </summary>
        internal static string ChangePasswordButtonType_FriendlyName {
            get {
                return ResourceManager.GetString("ChangePasswordButtonType_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        internal static string ChangePasswordFailureText_Category {
            get {
                return ResourceManager.GetString("ChangePasswordFailureText_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password incorrect or New Password invalid. New Password length minimum: {0}. Non-alphanumeric characters required: {1}..
        /// </summary>
        internal static string ChangePasswordFailureText_DefaultValue {
            get {
                return ResourceManager.GetString("ChangePasswordFailureText_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChangePasswordFailureText_Description {
            get {
                return ResourceManager.GetString("ChangePasswordFailureText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password Failure Text.
        /// </summary>
        internal static string ChangePasswordFailureText_FriendlyName {
            get {
                return ResourceManager.GetString("ChangePasswordFailureText_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string ChangePasswordTemplate_Category {
            get {
                return ResourceManager.GetString("ChangePasswordTemplate_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /_layouts/FBA/WEBPARTS/ChangePasswordWebPart/ChangePasswordTemplate.ascx.
        /// </summary>
        internal static string ChangePasswordTemplate_DefaultValue {
            get {
                return ResourceManager.GetString("ChangePasswordTemplate_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChangePasswordTemplate_Description {
            get {
                return ResourceManager.GetString("ChangePasswordTemplate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password Template.
        /// </summary>
        internal static string ChangePasswordTemplate_FriendlyName {
            get {
                return ResourceManager.GetString("ChangePasswordTemplate_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string ChangePasswordTitleText_Category {
            get {
                return ResourceManager.GetString("ChangePasswordTitleText_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Your Password.
        /// </summary>
        internal static string ChangePasswordTitleText_DefaultValue {
            get {
                return ResourceManager.GetString("ChangePasswordTitleText_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChangePasswordTitleText_Description {
            get {
                return ResourceManager.GetString("ChangePasswordTitleText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password Title Text.
        /// </summary>
        internal static string ChangePasswordTitleText_FriendlyName {
            get {
                return ResourceManager.GetString("ChangePasswordTitleText_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string ConfirmNewPasswordLabelText_Category {
            get {
                return ResourceManager.GetString("ConfirmNewPasswordLabelText_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password:.
        /// </summary>
        internal static string ConfirmNewPasswordLabelText_DefaultValue {
            get {
                return ResourceManager.GetString("ConfirmNewPasswordLabelText_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ConfirmNewPasswordLabelText_Description {
            get {
                return ResourceManager.GetString("ConfirmNewPasswordLabelText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password Label Text.
        /// </summary>
        internal static string ConfirmNewPasswordLabelText_FriendlyName {
            get {
                return ResourceManager.GetString("ConfirmNewPasswordLabelText_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        internal static string ConfirmPasswordCompareErrorMessage_Category {
            get {
                return ResourceManager.GetString("ConfirmPasswordCompareErrorMessage_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Confirm New Password must match the New Password entry..
        /// </summary>
        internal static string ConfirmPasswordCompareErrorMessage_DefaultValue {
            get {
                return ResourceManager.GetString("ConfirmPasswordCompareErrorMessage_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ConfirmPasswordCompareErrorMessage_Description {
            get {
                return ResourceManager.GetString("ConfirmPasswordCompareErrorMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password Compare Error Message.
        /// </summary>
        internal static string ConfirmPasswordCompareErrorMessage_FriendlyName {
            get {
                return ResourceManager.GetString("ConfirmPasswordCompareErrorMessage_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        internal static string ConfirmPasswordRequiredErrorMessage_Category {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequiredErrorMessage_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password is required..
        /// </summary>
        internal static string ConfirmPasswordRequiredErrorMessage_DefaultValue {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequiredErrorMessage_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ConfirmPasswordRequiredErrorMessage_Description {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequiredErrorMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password Required Error Message.
        /// </summary>
        internal static string ConfirmPasswordRequiredErrorMessage_FriendlyName {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequiredErrorMessage_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string ContinueButtonImageUrl_Category {
            get {
                return ResourceManager.GetString("ContinueButtonImageUrl_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ContinueButtonImageUrl_DefaultValue {
            get {
                return ResourceManager.GetString("ContinueButtonImageUrl_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ContinueButtonImageUrl_Description {
            get {
                return ResourceManager.GetString("ContinueButtonImageUrl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Button Image Url.
        /// </summary>
        internal static string ContinueButtonImageUrl_FriendlyName {
            get {
                return ResourceManager.GetString("ContinueButtonImageUrl_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string ContinueButtonText_Category {
            get {
                return ResourceManager.GetString("ContinueButtonText_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string ContinueButtonText_DefaultValue {
            get {
                return ResourceManager.GetString("ContinueButtonText_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ContinueButtonText_Description {
            get {
                return ResourceManager.GetString("ContinueButtonText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Button Text.
        /// </summary>
        internal static string ContinueButtonText_FriendlyName {
            get {
                return ResourceManager.GetString("ContinueButtonText_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string ContinueButtonType_Category {
            get {
                return ResourceManager.GetString("ContinueButtonType_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string ContinueButtonType_DefaultValue {
            get {
                return ResourceManager.GetString("ContinueButtonType_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ContinueButtonType_Description {
            get {
                return ResourceManager.GetString("ContinueButtonType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Button Type.
        /// </summary>
        internal static string ContinueButtonType_FriendlyName {
            get {
                return ResourceManager.GetString("ContinueButtonType_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string ContinueDestinationPageUrl_Category {
            get {
                return ResourceManager.GetString("ContinueDestinationPageUrl_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ContinueDestinationPageUrl_DefaultValue {
            get {
                return ResourceManager.GetString("ContinueDestinationPageUrl_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ContinueDestinationPageUrl_Description {
            get {
                return ResourceManager.GetString("ContinueDestinationPageUrl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Destination Page Url.
        /// </summary>
        internal static string ContinueDestinationPageUrl_FriendlyName {
            get {
                return ResourceManager.GetString("ContinueDestinationPageUrl_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string CreateUserIconUrl_Category {
            get {
                return ResourceManager.GetString("CreateUserIconUrl_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CreateUserIconUrl_DefaultValue {
            get {
                return ResourceManager.GetString("CreateUserIconUrl_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CreateUserIconUrl_Description {
            get {
                return ResourceManager.GetString("CreateUserIconUrl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User Icon Url.
        /// </summary>
        internal static string CreateUserIconUrl_FriendlyName {
            get {
                return ResourceManager.GetString("CreateUserIconUrl_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string CreateUserText_Category {
            get {
                return ResourceManager.GetString("CreateUserText_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CreateUserText_DefaultValue {
            get {
                return ResourceManager.GetString("CreateUserText_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CreateUserText_Description {
            get {
                return ResourceManager.GetString("CreateUserText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User Text.
        /// </summary>
        internal static string CreateUserText_FriendlyName {
            get {
                return ResourceManager.GetString("CreateUserText_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string CreateUserUrl_Category {
            get {
                return ResourceManager.GetString("CreateUserUrl_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CreateUserUrl_DefaultValue {
            get {
                return ResourceManager.GetString("CreateUserUrl_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CreateUserUrl_Description {
            get {
                return ResourceManager.GetString("CreateUserUrl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User Url.
        /// </summary>
        internal static string CreateUserUrl_FriendlyName {
            get {
                return ResourceManager.GetString("CreateUserUrl_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior.
        /// </summary>
        internal static string DisplayUserName_Category {
            get {
                return ResourceManager.GetString("DisplayUserName_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        internal static string DisplayUserName_DefaultValue {
            get {
                return ResourceManager.GetString("DisplayUserName_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DisplayUserName_Description {
            get {
                return ResourceManager.GetString("DisplayUserName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display User Name.
        /// </summary>
        internal static string DisplayUserName_FriendlyName {
            get {
                return ResourceManager.GetString("DisplayUserName_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string EditProfileIconUrl_Category {
            get {
                return ResourceManager.GetString("EditProfileIconUrl_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EditProfileIconUrl_DefaultValue {
            get {
                return ResourceManager.GetString("EditProfileIconUrl_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EditProfileIconUrl_Description {
            get {
                return ResourceManager.GetString("EditProfileIconUrl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile Icon Url.
        /// </summary>
        internal static string EditProfileIconUrl_FriendlyName {
            get {
                return ResourceManager.GetString("EditProfileIconUrl_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string EditProfileText_Category {
            get {
                return ResourceManager.GetString("EditProfileText_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EditProfileText_DefaultValue {
            get {
                return ResourceManager.GetString("EditProfileText_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EditProfileText_Description {
            get {
                return ResourceManager.GetString("EditProfileText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile Text.
        /// </summary>
        internal static string EditProfileText_FriendlyName {
            get {
                return ResourceManager.GetString("EditProfileText_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string EditProfileUrl_Category {
            get {
                return ResourceManager.GetString("EditProfileUrl_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EditProfileUrl_DefaultValue {
            get {
                return ResourceManager.GetString("EditProfileUrl_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EditProfileUrl_Description {
            get {
                return ResourceManager.GetString("EditProfileUrl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile Url.
        /// </summary>
        internal static string EditProfileUrl_FriendlyName {
            get {
                return ResourceManager.GetString("EditProfileUrl_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error in Change Password web part..
        /// </summary>
        internal static string Error_Message {
            get {
                return ResourceManager.GetString("Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string HelpPageIconUrl_Category {
            get {
                return ResourceManager.GetString("HelpPageIconUrl_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HelpPageIconUrl_DefaultValue {
            get {
                return ResourceManager.GetString("HelpPageIconUrl_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HelpPageIconUrl_Description {
            get {
                return ResourceManager.GetString("HelpPageIconUrl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Page Icon Url.
        /// </summary>
        internal static string HelpPageIconUrl_FriendlyName {
            get {
                return ResourceManager.GetString("HelpPageIconUrl_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string HelpPageText_Category {
            get {
                return ResourceManager.GetString("HelpPageText_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HelpPageText_DefaultValue {
            get {
                return ResourceManager.GetString("HelpPageText_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HelpPageText_Description {
            get {
                return ResourceManager.GetString("HelpPageText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Page Text.
        /// </summary>
        internal static string HelpPageText_FriendlyName {
            get {
                return ResourceManager.GetString("HelpPageText_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string HelpPageUrl_Category {
            get {
                return ResourceManager.GetString("HelpPageUrl_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HelpPageUrl_DefaultValue {
            get {
                return ResourceManager.GetString("HelpPageUrl_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HelpPageUrl_Description {
            get {
                return ResourceManager.GetString("HelpPageUrl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Page Url.
        /// </summary>
        internal static string HelpPageUrl_FriendlyName {
            get {
                return ResourceManager.GetString("HelpPageUrl_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string InstructionText_Category {
            get {
                return ResourceManager.GetString("InstructionText_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InstructionText_DefaultValue {
            get {
                return ResourceManager.GetString("InstructionText_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InstructionText_Description {
            get {
                return ResourceManager.GetString("InstructionText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction Text.
        /// </summary>
        internal static string InstructionText_FriendlyName {
            get {
                return ResourceManager.GetString("InstructionText_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string NewPasswordLabelText_Category {
            get {
                return ResourceManager.GetString("NewPasswordLabelText_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password:.
        /// </summary>
        internal static string NewPasswordLabelText_DefaultValue {
            get {
                return ResourceManager.GetString("NewPasswordLabelText_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NewPasswordLabelText_Description {
            get {
                return ResourceManager.GetString("NewPasswordLabelText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password Label Text.
        /// </summary>
        internal static string NewPasswordLabelText_FriendlyName {
            get {
                return ResourceManager.GetString("NewPasswordLabelText_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        internal static string NewPasswordRegularExpressionErrorMessage_Category {
            get {
                return ResourceManager.GetString("NewPasswordRegularExpressionErrorMessage_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a different password..
        /// </summary>
        internal static string NewPasswordRegularExpressionErrorMessage_DefaultValue {
            get {
                return ResourceManager.GetString("NewPasswordRegularExpressionErrorMessage_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NewPasswordRegularExpressionErrorMessage_Description {
            get {
                return ResourceManager.GetString("NewPasswordRegularExpressionErrorMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password Regular Expression Error Message.
        /// </summary>
        internal static string NewPasswordRegularExpressionErrorMessage_FriendlyName {
            get {
                return ResourceManager.GetString("NewPasswordRegularExpressionErrorMessage_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        internal static string NewPasswordRequiredErrorMessage_Category {
            get {
                return ResourceManager.GetString("NewPasswordRequiredErrorMessage_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password is required..
        /// </summary>
        internal static string NewPasswordRequiredErrorMessage_DefaultValue {
            get {
                return ResourceManager.GetString("NewPasswordRequiredErrorMessage_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NewPasswordRequiredErrorMessage_Description {
            get {
                return ResourceManager.GetString("NewPasswordRequiredErrorMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password Required Error Message.
        /// </summary>
        internal static string NewPasswordRequiredErrorMessage_FriendlyName {
            get {
                return ResourceManager.GetString("NewPasswordRequiredErrorMessage_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string PasswordHintText_Category {
            get {
                return ResourceManager.GetString("PasswordHintText_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PasswordHintText_DefaultValue {
            get {
                return ResourceManager.GetString("PasswordHintText_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PasswordHintText_Description {
            get {
                return ResourceManager.GetString("PasswordHintText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Hint Text.
        /// </summary>
        internal static string PasswordHintText_FriendlyName {
            get {
                return ResourceManager.GetString("PasswordHintText_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string PasswordLabelText_Category {
            get {
                return ResourceManager.GetString("PasswordLabelText_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string PasswordLabelText_DefaultValue {
            get {
                return ResourceManager.GetString("PasswordLabelText_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PasswordLabelText_Description {
            get {
                return ResourceManager.GetString("PasswordLabelText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Label Text.
        /// </summary>
        internal static string PasswordLabelText_FriendlyName {
            get {
                return ResourceManager.GetString("PasswordLabelText_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string PasswordRecoveryIconUrl_Category {
            get {
                return ResourceManager.GetString("PasswordRecoveryIconUrl_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PasswordRecoveryIconUrl_DefaultValue {
            get {
                return ResourceManager.GetString("PasswordRecoveryIconUrl_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PasswordRecoveryIconUrl_Description {
            get {
                return ResourceManager.GetString("PasswordRecoveryIconUrl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Recovery Icon Url.
        /// </summary>
        internal static string PasswordRecoveryIconUrl_FriendlyName {
            get {
                return ResourceManager.GetString("PasswordRecoveryIconUrl_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string PasswordRecoveryText_Category {
            get {
                return ResourceManager.GetString("PasswordRecoveryText_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PasswordRecoveryText_DefaultValue {
            get {
                return ResourceManager.GetString("PasswordRecoveryText_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PasswordRecoveryText_Description {
            get {
                return ResourceManager.GetString("PasswordRecoveryText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Recovery Text.
        /// </summary>
        internal static string PasswordRecoveryText_FriendlyName {
            get {
                return ResourceManager.GetString("PasswordRecoveryText_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string PasswordRecoveryUrl_Category {
            get {
                return ResourceManager.GetString("PasswordRecoveryUrl_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PasswordRecoveryUrl_DefaultValue {
            get {
                return ResourceManager.GetString("PasswordRecoveryUrl_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PasswordRecoveryUrl_Description {
            get {
                return ResourceManager.GetString("PasswordRecoveryUrl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Recovery Url.
        /// </summary>
        internal static string PasswordRecoveryUrl_FriendlyName {
            get {
                return ResourceManager.GetString("PasswordRecoveryUrl_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        internal static string PasswordRequiredErrorMessage_Category {
            get {
                return ResourceManager.GetString("PasswordRequiredErrorMessage_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        internal static string PasswordRequiredErrorMessage_DefaultValue {
            get {
                return ResourceManager.GetString("PasswordRequiredErrorMessage_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PasswordRequiredErrorMessage_Description {
            get {
                return ResourceManager.GetString("PasswordRequiredErrorMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Required Error Message.
        /// </summary>
        internal static string PasswordRequiredErrorMessage_FriendlyName {
            get {
                return ResourceManager.GetString("PasswordRequiredErrorMessage_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string SuccessPageUrl_Category {
            get {
                return ResourceManager.GetString("SuccessPageUrl_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SuccessPageUrl_DefaultValue {
            get {
                return ResourceManager.GetString("SuccessPageUrl_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SuccessPageUrl_Description {
            get {
                return ResourceManager.GetString("SuccessPageUrl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success Page Url.
        /// </summary>
        internal static string SuccessPageUrl_FriendlyName {
            get {
                return ResourceManager.GetString("SuccessPageUrl_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string SuccessTemplate_Category {
            get {
                return ResourceManager.GetString("SuccessTemplate_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /_layouts/FBA/WEBPARTS/ChangePasswordWebPart/SuccessTemplate.ascx.
        /// </summary>
        internal static string SuccessTemplate_DefaultValue {
            get {
                return ResourceManager.GetString("SuccessTemplate_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SuccessTemplate_Description {
            get {
                return ResourceManager.GetString("SuccessTemplate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success Template.
        /// </summary>
        internal static string SuccessTemplate_FriendlyName {
            get {
                return ResourceManager.GetString("SuccessTemplate_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string SuccessText_Category {
            get {
                return ResourceManager.GetString("SuccessText_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed!.
        /// </summary>
        internal static string SuccessText_DefaultValue {
            get {
                return ResourceManager.GetString("SuccessText_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SuccessText_Description {
            get {
                return ResourceManager.GetString("SuccessText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success Text.
        /// </summary>
        internal static string SuccessText_FriendlyName {
            get {
                return ResourceManager.GetString("SuccessText_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        internal static string ToolTip_Category {
            get {
                return ResourceManager.GetString("ToolTip_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ToolTip_DefaultValue {
            get {
                return ResourceManager.GetString("ToolTip_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ToolTip_Description {
            get {
                return ResourceManager.GetString("ToolTip_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Tip.
        /// </summary>
        internal static string ToolTip_FriendlyName {
            get {
                return ResourceManager.GetString("ToolTip_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string UserNameLabelText_Category {
            get {
                return ResourceManager.GetString("UserNameLabelText_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name:.
        /// </summary>
        internal static string UserNameLabelText_DefaultValue {
            get {
                return ResourceManager.GetString("UserNameLabelText_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UserNameLabelText_Description {
            get {
                return ResourceManager.GetString("UserNameLabelText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name Label Text.
        /// </summary>
        internal static string UserNameLabelText_FriendlyName {
            get {
                return ResourceManager.GetString("UserNameLabelText_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        internal static string UserNameRequiredErrorMessage_Category {
            get {
                return ResourceManager.GetString("UserNameRequiredErrorMessage_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name is required..
        /// </summary>
        internal static string UserNameRequiredErrorMessage_DefaultValue {
            get {
                return ResourceManager.GetString("UserNameRequiredErrorMessage_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UserNameRequiredErrorMessage_Description {
            get {
                return ResourceManager.GetString("UserNameRequiredErrorMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name Required Error Message.
        /// </summary>
        internal static string UserNameRequiredErrorMessage_FriendlyName {
            get {
                return ResourceManager.GetString("UserNameRequiredErrorMessage_FriendlyName", resourceCulture);
            }
        }
    }
}
