//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visigo.Sharepoint.FormsBasedAuthentication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FBAPackMembershipRequestWebPart {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FBAPackMembershipRequestWebPart() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Visigo.Sharepoint.FormsBasedAuthentication.Resources.FBAPackMembershipRequestWebP" +
                            "art", typeof(FBAPackMembershipRequestWebPart).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string AnswerLabelText_Category {
            get {
                return ResourceManager.GetString("AnswerLabelText_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Answer: .
        /// </summary>
        internal static string AnswerLabelText_DefaultValue {
            get {
                return ResourceManager.GetString("AnswerLabelText_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AnswerLabelText_Description {
            get {
                return ResourceManager.GetString("AnswerLabelText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer Label.
        /// </summary>
        internal static string AnswerLabelText_FriendlyName {
            get {
                return ResourceManager.GetString("AnswerLabelText_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        internal static string AnswerRequiredErrorMessage_Category {
            get {
                return ResourceManager.GetString("AnswerRequiredErrorMessage_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security answer is required..
        /// </summary>
        internal static string AnswerRequiredErrorMessage_DefaultValue {
            get {
                return ResourceManager.GetString("AnswerRequiredErrorMessage_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AnswerRequiredErrorMessage_Description {
            get {
                return ResourceManager.GetString("AnswerRequiredErrorMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer Required Error Message.
        /// </summary>
        internal static string AnswerRequiredErrorMessage_FriendlyName {
            get {
                return ResourceManager.GetString("AnswerRequiredErrorMessage_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string CancelButtonImageUrl_Category {
            get {
                return ResourceManager.GetString("CancelButtonImageUrl_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CancelButtonImageUrl_DefaultValue {
            get {
                return ResourceManager.GetString("CancelButtonImageUrl_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CancelButtonImageUrl_Description {
            get {
                return ResourceManager.GetString("CancelButtonImageUrl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Button Image Url.
        /// </summary>
        internal static string CancelButtonImageUrl_FriendlyName {
            get {
                return ResourceManager.GetString("CancelButtonImageUrl_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string CancelButtonText_Category {
            get {
                return ResourceManager.GetString("CancelButtonText_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelButtonText_DefaultValue {
            get {
                return ResourceManager.GetString("CancelButtonText_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CancelButtonText_Description {
            get {
                return ResourceManager.GetString("CancelButtonText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Button Text.
        /// </summary>
        internal static string CancelButtonText_FriendlyName {
            get {
                return ResourceManager.GetString("CancelButtonText_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string CancelButtonType_Category {
            get {
                return ResourceManager.GetString("CancelButtonType_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string CancelButtonType_DefaultValue {
            get {
                return ResourceManager.GetString("CancelButtonType_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CancelButtonType_Description {
            get {
                return ResourceManager.GetString("CancelButtonType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Button Type.
        /// </summary>
        internal static string CancelButtonType_FriendlyName {
            get {
                return ResourceManager.GetString("CancelButtonType_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string CancelDestinationPageUrl_Category {
            get {
                return ResourceManager.GetString("CancelDestinationPageUrl_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CancelDestinationPageUrl_DefaultValue {
            get {
                return ResourceManager.GetString("CancelDestinationPageUrl_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CancelDestinationPageUrl_Description {
            get {
                return ResourceManager.GetString("CancelDestinationPageUrl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Destination Page Url.
        /// </summary>
        internal static string CancelDestinationPageUrl_FriendlyName {
            get {
                return ResourceManager.GetString("CancelDestinationPageUrl_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CompleteSucccessText_Description {
            get {
                return ResourceManager.GetString("CompleteSucccessText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string CompleteSuccessText_Category {
            get {
                return ResourceManager.GetString("CompleteSuccessText_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your registration request has been received..
        /// </summary>
        internal static string CompleteSuccessText_DefaultValue {
            get {
                return ResourceManager.GetString("CompleteSuccessText_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Success Text.
        /// </summary>
        internal static string CompleteSuccessText_FriendlyName {
            get {
                return ResourceManager.GetString("CompleteSuccessText_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string CreateUserButtonImageUrl_Category {
            get {
                return ResourceManager.GetString("CreateUserButtonImageUrl_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CreateUserButtonImageUrl_DefaultValue {
            get {
                return ResourceManager.GetString("CreateUserButtonImageUrl_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CreateUserButtonImageUrl_Description {
            get {
                return ResourceManager.GetString("CreateUserButtonImageUrl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User Button Image Url.
        /// </summary>
        internal static string CreateUserButtonImageUrl_FriendlyName {
            get {
                return ResourceManager.GetString("CreateUserButtonImageUrl_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string CreateUserButtonText_Category {
            get {
                return ResourceManager.GetString("CreateUserButtonText_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User.
        /// </summary>
        internal static string CreateUserButtonText_DefaultValue {
            get {
                return ResourceManager.GetString("CreateUserButtonText_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CreateUserButtonText_Description {
            get {
                return ResourceManager.GetString("CreateUserButtonText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User Button Text.
        /// </summary>
        internal static string CreateUserButtonText_FriendlyName {
            get {
                return ResourceManager.GetString("CreateUserButtonText_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string CreateUserButtonType_Category {
            get {
                return ResourceManager.GetString("CreateUserButtonType_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string CreateUserButtonType_DefaultValue {
            get {
                return ResourceManager.GetString("CreateUserButtonType_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CreateUserButtonType_Description {
            get {
                return ResourceManager.GetString("CreateUserButtonType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User Button Type.
        /// </summary>
        internal static string CreateUserButtonType_FriendlyName {
            get {
                return ResourceManager.GetString("CreateUserButtonType_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styles.
        /// </summary>
        internal static string CssClass_Category {
            get {
                return ResourceManager.GetString("CssClass_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSS Class used to modify the appearance of the Registration Web Part.
        /// </summary>
        internal static string CssClass_Description {
            get {
                return ResourceManager.GetString("CssClass_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSS Class.
        /// </summary>
        internal static string CssClass_FriendlyName {
            get {
                return ResourceManager.GetString("CssClass_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior.
        /// </summary>
        internal static string DisplayCancelButton_Category {
            get {
                return ResourceManager.GetString("DisplayCancelButton_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        internal static string DisplayCancelButton_DefaultValue {
            get {
                return ResourceManager.GetString("DisplayCancelButton_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DisplayCancelButton_Description {
            get {
                return ResourceManager.GetString("DisplayCancelButton_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Cancel Button.
        /// </summary>
        internal static string DisplayCancelButton_FriendlyName {
            get {
                return ResourceManager.GetString("DisplayCancelButton_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        internal static string DuplicateEmailErrorMessage_Category {
            get {
                return ResourceManager.GetString("DuplicateEmailErrorMessage_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email you have entered is already in use. Please select another..
        /// </summary>
        internal static string DuplicateEmailErrorMessage_DefaultValue {
            get {
                return ResourceManager.GetString("DuplicateEmailErrorMessage_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DuplicateEmailErrorMessage_Description {
            get {
                return ResourceManager.GetString("DuplicateEmailErrorMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Email Error Message.
        /// </summary>
        internal static string DuplicateEmailErrorMessage_FriendlyName {
            get {
                return ResourceManager.GetString("DuplicateEmailErrorMessage_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        internal static string DuplicateUserNameErrorMessage_Category {
            get {
                return ResourceManager.GetString("DuplicateUserNameErrorMessage_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name you have entered is already in use. Please select another..
        /// </summary>
        internal static string DuplicateUserNameErrorMessage_DefaultValue {
            get {
                return ResourceManager.GetString("DuplicateUserNameErrorMessage_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DuplicateUserNameErrorMessage_Description {
            get {
                return ResourceManager.GetString("DuplicateUserNameErrorMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate User Name Error Message.
        /// </summary>
        internal static string DuplicateUserNameErrorMessage_FriendlyName {
            get {
                return ResourceManager.GetString("DuplicateUserNameErrorMessage_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string EditProfileIconUrl_Category {
            get {
                return ResourceManager.GetString("EditProfileIconUrl_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EditProfileIconUrl_DefaultValue {
            get {
                return ResourceManager.GetString("EditProfileIconUrl_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EditProfileIconUrl_Description {
            get {
                return ResourceManager.GetString("EditProfileIconUrl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile Icon Url.
        /// </summary>
        internal static string EditProfileIconUrl_FriendlyName {
            get {
                return ResourceManager.GetString("EditProfileIconUrl_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string EditProfileText_Category {
            get {
                return ResourceManager.GetString("EditProfileText_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EditProfileText_DefaultValue {
            get {
                return ResourceManager.GetString("EditProfileText_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EditProfileText_Description {
            get {
                return ResourceManager.GetString("EditProfileText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile Text.
        /// </summary>
        internal static string EditProfileText_FriendlyName {
            get {
                return ResourceManager.GetString("EditProfileText_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string EditProfileUrl_Category {
            get {
                return ResourceManager.GetString("EditProfileUrl_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EditProfileUrl_DefaultValue {
            get {
                return ResourceManager.GetString("EditProfileUrl_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EditProfileUrl_Description {
            get {
                return ResourceManager.GetString("EditProfileUrl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile Url.
        /// </summary>
        internal static string EditProfileUrl_FriendlyName {
            get {
                return ResourceManager.GetString("EditProfileUrl_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string EmailLabelText_Category {
            get {
                return ResourceManager.GetString("EmailLabelText_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email: .
        /// </summary>
        internal static string EmailLabelText_DefaultValue {
            get {
                return ResourceManager.GetString("EmailLabelText_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EmailLabelText_Description {
            get {
                return ResourceManager.GetString("EmailLabelText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Label.
        /// </summary>
        internal static string EmailLabelText_FriendlyName {
            get {
                return ResourceManager.GetString("EmailLabelText_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        internal static string EmailRegularExpressionErrorMessage_Category {
            get {
                return ResourceManager.GetString("EmailRegularExpressionErrorMessage_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a different email.
        /// </summary>
        internal static string EmailRegularExpressionErrorMessage_DefaultValue {
            get {
                return ResourceManager.GetString("EmailRegularExpressionErrorMessage_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EmailRegularExpressionErrorMessage_Description {
            get {
                return ResourceManager.GetString("EmailRegularExpressionErrorMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Regular Expression Error Message.
        /// </summary>
        internal static string EmailRegularExpressionErrorMessage_FriendlyName {
            get {
                return ResourceManager.GetString("EmailRegularExpressionErrorMessage_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        internal static string EmailRequiredErrorMessage_Category {
            get {
                return ResourceManager.GetString("EmailRequiredErrorMessage_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        internal static string EmailRequiredErrorMessage_DefaultValue {
            get {
                return ResourceManager.GetString("EmailRequiredErrorMessage_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EmailRequiredErrorMessage_Description {
            get {
                return ResourceManager.GetString("EmailRequiredErrorMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Required Error Message.
        /// </summary>
        internal static string EmailRequiredErrorMessage_FriendlyName {
            get {
                return ResourceManager.GetString("EmailRequiredErrorMessage_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string FinishDestinationPageUrl_Category {
            get {
                return ResourceManager.GetString("FinishDestinationPageUrl_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FinishDestinationPageUrl_DefaultValue {
            get {
                return ResourceManager.GetString("FinishDestinationPageUrl_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FinishDestinationPageUrl_Description {
            get {
                return ResourceManager.GetString("FinishDestinationPageUrl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Destination Page Url.
        /// </summary>
        internal static string FinishDestinationPageUrl_FriendlyName {
            get {
                return ResourceManager.GetString("FinishDestinationPageUrl_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string FirstNameLabelText_Category {
            get {
                return ResourceManager.GetString("FirstNameLabelText_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name: .
        /// </summary>
        internal static string FirstNameLabelText_DefaultValue {
            get {
                return ResourceManager.GetString("FirstNameLabelText_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FirstNameLabelText_Description {
            get {
                return ResourceManager.GetString("FirstNameLabelText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name Label.
        /// </summary>
        internal static string FirstNameLabelText_FriendlyName {
            get {
                return ResourceManager.GetString("FirstNameLabelText_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        internal static string FirstNameRequiredErrorMessage_Category {
            get {
                return ResourceManager.GetString("FirstNameRequiredErrorMessage_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string FirstNameRequiredErrorMessage_DefaultValue {
            get {
                return ResourceManager.GetString("FirstNameRequiredErrorMessage_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FirstNameRequiredErrorMessage_Description {
            get {
                return ResourceManager.GetString("FirstNameRequiredErrorMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name Required Error Message.
        /// </summary>
        internal static string FirstNameRequiredErrorMessage_FriendlyName {
            get {
                return ResourceManager.GetString("FirstNameRequiredErrorMessage_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select A Default Group For All New Registrants.
        /// </summary>
        internal static string GroupEditor_Description {
            get {
                return ResourceManager.GetString("GroupEditor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Group For New Users.
        /// </summary>
        internal static string GroupEditor_Title {
            get {
                return ResourceManager.GetString("GroupEditor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string HeaderText_Category {
            get {
                return ResourceManager.GetString("HeaderText_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HeaderText_DefaultValue {
            get {
                return ResourceManager.GetString("HeaderText_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HeaderText_Description {
            get {
                return ResourceManager.GetString("HeaderText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header Text.
        /// </summary>
        internal static string HeaderText_FriendlyName {
            get {
                return ResourceManager.GetString("HeaderText_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string HipCharactersLabelText_Category {
            get {
                return ResourceManager.GetString("HipCharactersLabelText_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters: .
        /// </summary>
        internal static string HipCharactersLabelText_DefaultValue {
            get {
                return ResourceManager.GetString("HipCharactersLabelText_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HipCharactersLabelText_Description {
            get {
                return ResourceManager.GetString("HipCharactersLabelText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIP Characters.
        /// </summary>
        internal static string HipCharactersLabelText_FriendlyName {
            get {
                return ResourceManager.GetString("HipCharactersLabelText_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        internal static string HipErrorMessage_Category {
            get {
                return ResourceManager.GetString("HipErrorMessage_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string HipErrorMessage_DefaultValue {
            get {
                return ResourceManager.GetString("HipErrorMessage_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HipErrorMessage_Description {
            get {
                return ResourceManager.GetString("HipErrorMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIP Error Message.
        /// </summary>
        internal static string HipErrorMessage_FriendlyName {
            get {
                return ResourceManager.GetString("HipErrorMessage_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string HipInstructionsLabelText_Category {
            get {
                return ResourceManager.GetString("HipInstructionsLabelText_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the characters in the picture below..
        /// </summary>
        internal static string HipInstructionsLabelText_DefaultValue {
            get {
                return ResourceManager.GetString("HipInstructionsLabelText_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HipInstructionsLabelText_Description {
            get {
                return ResourceManager.GetString("HipInstructionsLabelText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIP Instructions.
        /// </summary>
        internal static string HipInstructionsLabelText_FriendlyName {
            get {
                return ResourceManager.GetString("HipInstructionsLabelText_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        internal static string HipLengthErrorMessage_Category {
            get {
                return ResourceManager.GetString("HipLengthErrorMessage_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture characters may not be more than 20 characters..
        /// </summary>
        internal static string HipLengthErrorMessage_DefaultValue {
            get {
                return ResourceManager.GetString("HipLengthErrorMessage_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HipLengthErrorMessage_Description {
            get {
                return ResourceManager.GetString("HipLengthErrorMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIP Length Error Message.
        /// </summary>
        internal static string HipLengthErrorMessage_FriendlyName {
            get {
                return ResourceManager.GetString("HipLengthErrorMessage_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string HipPictureDescription_Category {
            get {
                return ResourceManager.GetString("HipPictureDescription_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The picture contains 6 characters..
        /// </summary>
        internal static string HipPictureDescription_DefaultValue {
            get {
                return ResourceManager.GetString("HipPictureDescription_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HipPictureDescription_Description {
            get {
                return ResourceManager.GetString("HipPictureDescription_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIP Picture Description.
        /// </summary>
        internal static string HipPictureDescription_FriendlyName {
            get {
                return ResourceManager.GetString("HipPictureDescription_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string HipPictureLabelText_Category {
            get {
                return ResourceManager.GetString("HipPictureLabelText_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture: .
        /// </summary>
        internal static string HipPictureLabelText_DefaultValue {
            get {
                return ResourceManager.GetString("HipPictureLabelText_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HipPictureLabelText_Description {
            get {
                return ResourceManager.GetString("HipPictureLabelText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIP Picture Message.
        /// </summary>
        internal static string HipPictureLabelText_FriendlyName {
            get {
                return ResourceManager.GetString("HipPictureLabelText_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string HipResetLabelText_Category {
            get {
                return ResourceManager.GetString("HipResetLabelText_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t see the word?.
        /// </summary>
        internal static string HipResetLabelText_DefaultValue {
            get {
                return ResourceManager.GetString("HipResetLabelText_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HipResetLabelText_Description {
            get {
                return ResourceManager.GetString("HipResetLabelText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIP Reset Message.
        /// </summary>
        internal static string HipResetLabelText_FriendlyName {
            get {
                return ResourceManager.GetString("HipResetLabelText_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string InstructionText_Category {
            get {
                return ResourceManager.GetString("InstructionText_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InstructionText_DefaultValue {
            get {
                return ResourceManager.GetString("InstructionText_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InstructionText_Description {
            get {
                return ResourceManager.GetString("InstructionText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction Text.
        /// </summary>
        internal static string InstructionText_FriendlyName {
            get {
                return ResourceManager.GetString("InstructionText_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        internal static string InvalidAnswerErrorMessage_Category {
            get {
                return ResourceManager.GetString("InvalidAnswerErrorMessage_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a different security answer..
        /// </summary>
        internal static string InvalidAnswerErrorMessage_DefaultValue {
            get {
                return ResourceManager.GetString("InvalidAnswerErrorMessage_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InvalidAnswerErrorMessage_Description {
            get {
                return ResourceManager.GetString("InvalidAnswerErrorMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Answer Error Message.
        /// </summary>
        internal static string InvalidAnswerErrorMessage_FriendlyName {
            get {
                return ResourceManager.GetString("InvalidAnswerErrorMessage_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        internal static string InvalidEmailErrorMessage_Category {
            get {
                return ResourceManager.GetString("InvalidEmailErrorMessage_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address..
        /// </summary>
        internal static string InvalidEmailErrorMessage_DefaultValue {
            get {
                return ResourceManager.GetString("InvalidEmailErrorMessage_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InvalidEmailErrorMessage_Description {
            get {
                return ResourceManager.GetString("InvalidEmailErrorMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email Error Message.
        /// </summary>
        internal static string InvalidEmailErrorMessage_FriendlyName {
            get {
                return ResourceManager.GetString("InvalidEmailErrorMessage_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        internal static string InvalidQuestionErrorMessage_Category {
            get {
                return ResourceManager.GetString("InvalidQuestionErrorMessage_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a different security question..
        /// </summary>
        internal static string InvalidQuestionErrorMessage_DefaultValue {
            get {
                return ResourceManager.GetString("InvalidQuestionErrorMessage_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InvalidQuestionErrorMessage_Description {
            get {
                return ResourceManager.GetString("InvalidQuestionErrorMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Question Error Message .
        /// </summary>
        internal static string InvalidQuestionErrorMessage_FriendlyName {
            get {
                return ResourceManager.GetString("InvalidQuestionErrorMessage_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string LastNameLabelText_Category {
            get {
                return ResourceManager.GetString("LastNameLabelText_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name: .
        /// </summary>
        internal static string LastNameLabelText_DefaultValue {
            get {
                return ResourceManager.GetString("LastNameLabelText_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LastNameLabelText_Description {
            get {
                return ResourceManager.GetString("LastNameLabelText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name Label.
        /// </summary>
        internal static string LastNameLabelText_FriendlyName {
            get {
                return ResourceManager.GetString("LastNameLabelText_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        internal static string LastNameRequiredErrorMessage_Category {
            get {
                return ResourceManager.GetString("LastNameRequiredErrorMessage_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string LastNameRequiredErrorMessage_DefaultValue {
            get {
                return ResourceManager.GetString("LastNameRequiredErrorMessage_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LastNameRequiredErrorMessage_Description {
            get {
                return ResourceManager.GetString("LastNameRequiredErrorMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name Required Error Message.
        /// </summary>
        internal static string LastNameRequiredErrorMessage_FriendlyName {
            get {
                return ResourceManager.GetString("LastNameRequiredErrorMessage_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior.
        /// </summary>
        internal static string LoginCreatedUser_Category {
            get {
                return ResourceManager.GetString("LoginCreatedUser_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        internal static string LoginCreatedUser_DefaultValue {
            get {
                return ResourceManager.GetString("LoginCreatedUser_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LoginCreatedUser_Description {
            get {
                return ResourceManager.GetString("LoginCreatedUser_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Created User.
        /// </summary>
        internal static string LoginCreatedUser_FriendlyName {
            get {
                return ResourceManager.GetString("LoginCreatedUser_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your membership request has been received..
        /// </summary>
        internal static string MembershipRequestConfirmationMessage {
            get {
                return ResourceManager.GetString("MembershipRequestConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string QuestionLabelText_Category {
            get {
                return ResourceManager.GetString("QuestionLabelText_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Question: .
        /// </summary>
        internal static string QuestionLabelText_DefaultValue {
            get {
                return ResourceManager.GetString("QuestionLabelText_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string QuestionLabelText_Description {
            get {
                return ResourceManager.GetString("QuestionLabelText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Label.
        /// </summary>
        internal static string QuestionLabelText_FriendlyName {
            get {
                return ResourceManager.GetString("QuestionLabelText_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        internal static string QuestionRequiredErrorMessage_Category {
            get {
                return ResourceManager.GetString("QuestionRequiredErrorMessage_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security question is required..
        /// </summary>
        internal static string QuestionRequiredErrorMessage_DefaultValue {
            get {
                return ResourceManager.GetString("QuestionRequiredErrorMessage_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string QuestionRequiredErrorMessage_Description {
            get {
                return ResourceManager.GetString("QuestionRequiredErrorMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Required Error Message.
        /// </summary>
        internal static string QuestionRequiredErrorMessage_FriendlyName {
            get {
                return ResourceManager.GetString("QuestionRequiredErrorMessage_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string RequiredFieldText_Category {
            get {
                return ResourceManager.GetString("RequiredFieldText_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string RequiredFieldText_DefaultValue {
            get {
                return ResourceManager.GetString("RequiredFieldText_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RequiredFieldText_Description {
            get {
                return ResourceManager.GetString("RequiredFieldText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field Text.
        /// </summary>
        internal static string RequiredFieldText_FriendlyName {
            get {
                return ResourceManager.GetString("RequiredFieldText_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        internal static string UnknownErrorMessage_Category {
            get {
                return ResourceManager.GetString("UnknownErrorMessage_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error.
        /// </summary>
        internal static string UnknownErrorMessage_DefaultValue {
            get {
                return ResourceManager.GetString("UnknownErrorMessage_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UnknownErrorMessage_Description {
            get {
                return ResourceManager.GetString("UnknownErrorMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error Message.
        /// </summary>
        internal static string UnknownErrorMessage_FriendlyName {
            get {
                return ResourceManager.GetString("UnknownErrorMessage_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string UserNameLabelText_Category {
            get {
                return ResourceManager.GetString("UserNameLabelText_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name: .
        /// </summary>
        internal static string UserNameLabelText_DefaultValue {
            get {
                return ResourceManager.GetString("UserNameLabelText_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UserNameLabelText_Description {
            get {
                return ResourceManager.GetString("UserNameLabelText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name Label.
        /// </summary>
        internal static string UserNameLabelText_FriendlyName {
            get {
                return ResourceManager.GetString("UserNameLabelText_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        internal static string UserNameRequiredErrorMessage_Category {
            get {
                return ResourceManager.GetString("UserNameRequiredErrorMessage_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name is required..
        /// </summary>
        internal static string UserNameRequiredErrorMessage_DefaultValue {
            get {
                return ResourceManager.GetString("UserNameRequiredErrorMessage_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UserNameRequiredErrorMessage_Description {
            get {
                return ResourceManager.GetString("UserNameRequiredErrorMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name Required Error Message.
        /// </summary>
        internal static string UserNameRequiredErrorMessage_FriendlyName {
            get {
                return ResourceManager.GetString("UserNameRequiredErrorMessage_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        internal static string ValidationSummaryHeaderText_Category {
            get {
                return ResourceManager.GetString("ValidationSummaryHeaderText_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please correct the following items:.
        /// </summary>
        internal static string ValidationSummaryHeaderText_DefaultValue {
            get {
                return ResourceManager.GetString("ValidationSummaryHeaderText_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ValidationSummaryHeaderText_Description {
            get {
                return ResourceManager.GetString("ValidationSummaryHeaderText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Summary Header Text.
        /// </summary>
        internal static string ValidationSummaryHeaderText_FriendlyName {
            get {
                return ResourceManager.GetString("ValidationSummaryHeaderText_FriendlyName", resourceCulture);
            }
        }
    }
}
