//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visigo.Sharepoint.FormsBasedAuthentication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FBAPackPasswordRecoveryWebPart {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FBAPackPasswordRecoveryWebPart() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Visigo.Sharepoint.FormsBasedAuthentication.Resources.FBAPackPasswordRecoveryWebPa" +
                            "rt", typeof(FBAPackPasswordRecoveryWebPart).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        internal static string AnswerRequiredErrorMessage_Category {
            get {
                return ResourceManager.GetString("AnswerRequiredErrorMessage_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer is required..
        /// </summary>
        internal static string AnswerRequiredErrorMessage_DefaultValue {
            get {
                return ResourceManager.GetString("AnswerRequiredErrorMessage_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AnswerRequiredErrorMessage_Description {
            get {
                return ResourceManager.GetString("AnswerRequiredErrorMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer Required Error Message.
        /// </summary>
        internal static string AnswerRequiredErrorMessage_FriendlyName {
            get {
                return ResourceManager.GetString("AnswerRequiredErrorMessage_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error sending the email, please check with your administrator.
        /// </summary>
        internal static string ErrorSendingEmail {
            get {
                return ResourceManager.GetString("ErrorSendingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        internal static string GeneralFailureText_Category {
            get {
                return ResourceManager.GetString("GeneralFailureText_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your attempt to retrieve your password was not successful. Please try again..
        /// </summary>
        internal static string GeneralFailureText_DefaultValue {
            get {
                return ResourceManager.GetString("GeneralFailureText_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GeneralFailureText_Description {
            get {
                return ResourceManager.GetString("GeneralFailureText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Failure Text.
        /// </summary>
        internal static string GeneralFailureText_FriendlyName {
            get {
                return ResourceManager.GetString("GeneralFailureText_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        internal static string QuestionFailureText_Category {
            get {
                return ResourceManager.GetString("QuestionFailureText_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your answer could not be verified. Please try again..
        /// </summary>
        internal static string QuestionFailureText_DefaultValue {
            get {
                return ResourceManager.GetString("QuestionFailureText_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string QuestionFailureText_Description {
            get {
                return ResourceManager.GetString("QuestionFailureText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Failure Text.
        /// </summary>
        internal static string QuestionFailureText_FriendlyName {
            get {
                return ResourceManager.GetString("QuestionFailureText_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string QuestionInstructionText_Category {
            get {
                return ResourceManager.GetString("QuestionInstructionText_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer the following question to receive your password..
        /// </summary>
        internal static string QuestionInstructionText_DefaultValue {
            get {
                return ResourceManager.GetString("QuestionInstructionText_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string QuestionInstructionText_Description {
            get {
                return ResourceManager.GetString("QuestionInstructionText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Instruction Text.
        /// </summary>
        internal static string QuestionInstructionText_FriendlyName {
            get {
                return ResourceManager.GetString("QuestionInstructionText_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string QuestionLabelText_Category {
            get {
                return ResourceManager.GetString("QuestionLabelText_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question:.
        /// </summary>
        internal static string QuestionLabelText_DefaultValue {
            get {
                return ResourceManager.GetString("QuestionLabelText_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string QuestionLabelText_Description {
            get {
                return ResourceManager.GetString("QuestionLabelText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Label Text.
        /// </summary>
        internal static string QuestionLabelText_FriendlyName {
            get {
                return ResourceManager.GetString("QuestionLabelText_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string QuestionTemplate_Category {
            get {
                return ResourceManager.GetString("QuestionTemplate_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /_layouts/FBA/WEBPARTS/PasswordRecoveryWebPart/QuestionTemplate.ascx.
        /// </summary>
        internal static string QuestionTemplate_DefaultValue {
            get {
                return ResourceManager.GetString("QuestionTemplate_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string QuestionTemplate_Description {
            get {
                return ResourceManager.GetString("QuestionTemplate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Template.
        /// </summary>
        internal static string QuestionTemplate_FriendlyName {
            get {
                return ResourceManager.GetString("QuestionTemplate_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string QuestionTitleText_Category {
            get {
                return ResourceManager.GetString("QuestionTitleText_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity Confirmation.
        /// </summary>
        internal static string QuestionTitleText_DefaultValue {
            get {
                return ResourceManager.GetString("QuestionTitleText_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string QuestionTitleText_Description {
            get {
                return ResourceManager.GetString("QuestionTitleText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Title Text.
        /// </summary>
        internal static string QuestionTitleText_FriendlyName {
            get {
                return ResourceManager.GetString("QuestionTitleText_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string SubmitButtonImageUrl_Category {
            get {
                return ResourceManager.GetString("SubmitButtonImageUrl_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SubmitButtonImageUrl_DefaultValue {
            get {
                return ResourceManager.GetString("SubmitButtonImageUrl_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SubmitButtonImageUrl_Description {
            get {
                return ResourceManager.GetString("SubmitButtonImageUrl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Button Image Url.
        /// </summary>
        internal static string SubmitButtonImageUrl_FriendlyName {
            get {
                return ResourceManager.GetString("SubmitButtonImageUrl_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string SubmitButtonText_Category {
            get {
                return ResourceManager.GetString("SubmitButtonText_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string SubmitButtonText_DefaultValue {
            get {
                return ResourceManager.GetString("SubmitButtonText_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SubmitButtonText_Description {
            get {
                return ResourceManager.GetString("SubmitButtonText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Button Text.
        /// </summary>
        internal static string SubmitButtonText_FriendlyName {
            get {
                return ResourceManager.GetString("SubmitButtonText_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string SubmitButtonType_Category {
            get {
                return ResourceManager.GetString("SubmitButtonType_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string SubmitButtonType_DefaultValue {
            get {
                return ResourceManager.GetString("SubmitButtonType_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SubmitButtonType_Description {
            get {
                return ResourceManager.GetString("SubmitButtonType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Button Type.
        /// </summary>
        internal static string SubmitButtonType_FriendlyName {
            get {
                return ResourceManager.GetString("SubmitButtonType_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string SuccessTemplate_Category {
            get {
                return ResourceManager.GetString("SuccessTemplate_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /_layouts/FBA/WEBPARTS/PasswordRecoveryWebPart/SuccessTemplate.ascx.
        /// </summary>
        internal static string SuccessTemplate_DefaultValue {
            get {
                return ResourceManager.GetString("SuccessTemplate_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SuccessTemplate_Description {
            get {
                return ResourceManager.GetString("SuccessTemplate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success Template.
        /// </summary>
        internal static string SuccessTemplate_FriendlyName {
            get {
                return ResourceManager.GetString("SuccessTemplate_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string SuccessText_Category {
            get {
                return ResourceManager.GetString("SuccessText_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been sent to you..
        /// </summary>
        internal static string SuccessText_DefaultValue {
            get {
                return ResourceManager.GetString("SuccessText_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SuccessText_Description {
            get {
                return ResourceManager.GetString("SuccessText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success Text.
        /// </summary>
        internal static string SuccessText_FriendlyName {
            get {
                return ResourceManager.GetString("SuccessText_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        internal static string UserNameFailureText_Category {
            get {
                return ResourceManager.GetString("UserNameFailureText_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We were unable to access your information. Please try again..
        /// </summary>
        internal static string UserNameFailureText_DefaultValue {
            get {
                return ResourceManager.GetString("UserNameFailureText_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UserNameFailureText_Description {
            get {
                return ResourceManager.GetString("UserNameFailureText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name Failure Text.
        /// </summary>
        internal static string UserNameFailureText_FriendlyName {
            get {
                return ResourceManager.GetString("UserNameFailureText_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string UserNameInstructionText_Category {
            get {
                return ResourceManager.GetString("UserNameInstructionText_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your User Name or Email Address to receive your password..
        /// </summary>
        internal static string UserNameInstructionText_DefaultValue {
            get {
                return ResourceManager.GetString("UserNameInstructionText_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UserNameInstructionText_Description {
            get {
                return ResourceManager.GetString("UserNameInstructionText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name Instruction Text.
        /// </summary>
        internal static string UserNameInstructionText_FriendlyName {
            get {
                return ResourceManager.GetString("UserNameInstructionText_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string UserNameLabelText_Category {
            get {
                return ResourceManager.GetString("UserNameLabelText_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name or Email Address:.
        /// </summary>
        internal static string UserNameLabelText_DefaultValue {
            get {
                return ResourceManager.GetString("UserNameLabelText_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UserNameLabelText_Description {
            get {
                return ResourceManager.GetString("UserNameLabelText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name Label Text.
        /// </summary>
        internal static string UserNameLabelText_FriendlyName {
            get {
                return ResourceManager.GetString("UserNameLabelText_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        internal static string UserNameRequiredErrorMessage_Category {
            get {
                return ResourceManager.GetString("UserNameRequiredErrorMessage_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name is required..
        /// </summary>
        internal static string UserNameRequiredErrorMessage_DefaultValue {
            get {
                return ResourceManager.GetString("UserNameRequiredErrorMessage_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UserNameRequiredErrorMessage_Description {
            get {
                return ResourceManager.GetString("UserNameRequiredErrorMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name Required Error Message.
        /// </summary>
        internal static string UserNameRequiredErrorMessage_FriendlyName {
            get {
                return ResourceManager.GetString("UserNameRequiredErrorMessage_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string UserNameTemplate_Category {
            get {
                return ResourceManager.GetString("UserNameTemplate_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /_layouts/FBA/WEBPARTS/PasswordRecoveryWebPart/UserNameTemplate.ascx.
        /// </summary>
        internal static string UserNameTemplate_DefaultValue {
            get {
                return ResourceManager.GetString("UserNameTemplate_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UserNameTemplate_Description {
            get {
                return ResourceManager.GetString("UserNameTemplate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName Template.
        /// </summary>
        internal static string UserNameTemplate_FriendlyName {
            get {
                return ResourceManager.GetString("UserNameTemplate_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string UserNameTitleText_Category {
            get {
                return ResourceManager.GetString("UserNameTitleText_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Your Password?.
        /// </summary>
        internal static string UserNameTitleText_DefaultValue {
            get {
                return ResourceManager.GetString("UserNameTitleText_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UserNameTitleText_Description {
            get {
                return ResourceManager.GetString("UserNameTitleText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name Title Text.
        /// </summary>
        internal static string UserNameTitleText_FriendlyName {
            get {
                return ResourceManager.GetString("UserNameTitleText_FriendlyName", resourceCulture);
            }
        }
    }
}
